# Generated by Django 5.2.7 on 2025-11-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Title')),
                ('requisites', models.CharField(unique=True, verbose_name='Requisites')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('surname', models.CharField(max_length=15, verbose_name='Surname')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Middle Name')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
                ('birthday', models.DateField(blank=True, verbose_name='Birthday')),
                ('city', models.CharField(max_length=25, verbose_name='City')),
                ('id_cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.cards', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Title')),
                ('img', models.ImageField(upload_to='Jewelry_imgs/', verbose_name='Foto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('description', models.CharField(default='', max_length=300, null=True, verbose_name='Desription')),
                ('old_price', models.DecimalField(decimal_places=2, default=45000, max_digits=20, verbose_name='Old price')),
                ('article', models.CharField(default='000000000000', max_length=12, verbose_name='Article')),
                ('material', models.CharField(default='Gold', max_length=50, verbose_name='Material')),
                ('insert', models.CharField(max_length=80, null=True, verbose_name='Insert')),
                ('country', models.CharField(default='Italy', max_length=64, verbose_name='Country')),
                ('weight', models.DecimalField(decimal_places=2, default=2.24, max_digits=5, verbose_name='Weight')),
                ('catalogs', models.ManyToManyField(to='jewelry_app.catalogs')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Final price')),
                ('status', models.CharField(choices=[('Being issued', 'Being issued'), ('On the way', 'On the way'), ('At the pick-up point', 'At the pick-up point')], max_length=1020, verbose_name='Status')),
                ('address', models.CharField(max_length=25, verbose_name='Address')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Client')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.cards', verbose_name='Payment')),
                ('products', models.ManyToManyField(to='jewelry_app.products')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=60, verbose_name='Product')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Client')),
                ('products', models.ManyToManyField(to='jewelry_app.products')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Special_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Name product')),
            ],
            options={
                'verbose_name': 'Special offer',
                'verbose_name_plural': 'Special offers',
            },
        ),
    ]
