# Generated by Django 5.2.7 on 2025-10-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('requisites', models.CharField(unique=True, verbose_name='Реквезиты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('img', models.CharField(max_length=60, verbose_name='Товар')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('description', models.TextField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('nik', models.CharField(max_length=20, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('id_cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.cards', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итоговая цена')),
                ('status', models.CharField(choices=[('Оформляется', 'Оформляется'), ('В пути', 'В пути'), ('На пункте выдачи', 'На пункте выдачи')], max_length=1020, verbose_name='Статус')),
                ('address', models.CharField(max_length=25, verbose_name='Адрес')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Клиент')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.cards', verbose_name='Оплата')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Products_catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catalogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.catalogs', verbose_name='Каталог')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в каталоге',
                'verbose_name_plural': 'Товары в каталогах',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('img', models.CharField(max_length=60, verbose_name='Товар')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Products_purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=3, verbose_name='Количество')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Товар')),
                ('id_purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.purchases', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар в покупке',
                'verbose_name_plural': 'Товары в покупках',
            },
        ),
        migrations.CreateModel(
            name='Special_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Специальное предложение',
                'verbose_name_plural': 'Специальные предложения',
            },
        ),
    ]
