# Generated by Django 5.2.7 on 2025-11-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special_offers',
        ),
    ]
