# Generated by Django 5.2.7 on 2025-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0002_delete_special_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='img',
            field=models.ImageField(upload_to='Jewelry_imgs/', verbose_name='Foto'),
        ),
    ]
