# Generated by Django 5.2.6 on 2025-10-08 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0002_alter_clients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_purchases',
            name='id_purchases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.purchases', verbose_name='Покупка'),
        ),
    ]
