# Generated by Django 5.2.6 on 2025-10-08 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0003_alter_products_purchases_id_purchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=3, verbose_name='Количество')),
                ('id_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.orders', verbose_name='Заказ')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
    ]
