# Generated by Django 5.2.7 on 2025-12-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0003_alter_purchases_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id_clients',
            new_name='clients',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='id_cards',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='id_clients',
        ),
        migrations.AddField(
            model_name='cards',
            name='clients',
            field=models.ManyToManyField(to='jewelry_app.clients'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='clients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateField(default='2025-12-03', verbose_name='Purchase date'),
        ),
    ]
