# Generated by Django 5.2.7 on 2025-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0004_rename_id_clients_orders_clients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='clients',
        ),
        migrations.AddField(
            model_name='clients',
            name='cards',
            field=models.ManyToManyField(to='jewelry_app.cards'),
        ),
    ]
