# Generated by Django 5.2.7 on 2025-10-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0004_products_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='name',
        ),
    ]
