# Generated by Django 5.2.7 on 2025-10-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0005_remove_purchases_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='nik',
            new_name='nickname',
        ),
    ]
