# Generated by Django 5.2.7 on 2025-11-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0006_rename_nik_clients_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AlterModelOptions(
            name='catalogs',
            options={'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='products_catalogs',
            options={'verbose_name': 'Product in catalog', 'verbose_name_plural': 'Products in catalogs'},
        ),
        migrations.AlterModelOptions(
            name='products_orders',
            options={'verbose_name': 'Product in the order', 'verbose_name_plural': 'Products in the orders'},
        ),
        migrations.AlterModelOptions(
            name='products_purchases',
            options={'verbose_name': 'Product in purchase', 'verbose_name_plural': 'Products in purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='special_offers',
            options={'verbose_name': 'Special offer', 'verbose_name_plural': 'Special offers'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='article',
            field=models.CharField(default='000000000000', max_length=12, verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.CharField(default='Italy', max_length=64, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='products',
            name='insert',
            field=models.CharField(max_length=80, null=True, verbose_name='Insert'),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(default='Gold', max_length=50, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=45000, max_digits=20, verbose_name='Old price'),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=2.24, max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='requisites',
            field=models.CharField(unique=True, verbose_name='Requisites'),
        ),
        migrations.AlterField(
            model_name='catalogs',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=models.CharField(max_length=25, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='id_cards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.cards', verbose_name='Card'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='middle_name',
            field=models.CharField(max_length=20, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(max_length=15, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=25, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.cards', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Being issued', 'Being issued'), ('On the way', 'On the way'), ('At the pick-up point', 'At the pick-up point')], max_length=1020, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='products_catalogs',
            name='id_catalogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.catalogs', verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='products_catalogs',
            name='id_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='products_orders',
            name='count',
            field=models.CharField(max_length=3, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='products_orders',
            name='id_orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.orders', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='products_orders',
            name='id_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='products_purchases',
            name='count',
            field=models.CharField(max_length=3, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='products_purchases',
            name='id_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='products_purchases',
            name='id_purchases',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.purchases', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='id_clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='img',
            field=models.CharField(max_length=60, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='special_offers',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='special_offers',
            name='id_products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry_app.products', verbose_name='Name product'),
        ),
    ]
