# Generated by Django 5.2.7 on 2025-11-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0007_alter_cards_options_alter_catalogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='material',
            field=models.CharField(default='Gold', max_length=50, verbose_name='Material'),
        ),
    ]
