# Generated by Django 5.2.7 on 2025-11-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0007_alter_cards_options_alter_catalogs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(upload_to='Jewelry_imgs/', verbose_name='Foto'),
        ),
    ]
