# Generated by Django 5.2.7 on 2025-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry_app', '0008_alter_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Desription'),
        ),
    ]
